

DROP TABLE IF EXISTS Oblivious CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Taskclass CASCADE;
DROP TABLE IF EXISTS Taskclassunion CASCADE;
DROP TABLE IF EXISTS Importance CASCADE;
DROP TABLE IF EXISTS Deadline CASCADE;