

DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Askareluokka CASCADE;
DROP TABLE IF EXISTS Askareluokkaliitos CASCADE;
DROP TABLE IF EXISTS Tarkeysaste CASCADE;
DROP TABLE IF EXISTS Deadline CASCADE;