

DROP TABLE IF EXISTS Oblivious CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Taskclass CASCADE;
DROP TABLE IF EXISTS Taskclassunion CASCADE;
DROP TABLE IF EXISTS Importance CASCADE;
DROP TABLE IF EXISTS Deadline CASCADE;

DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Askareluokka CASCADE;
DROP TABLE IF EXISTS Askareluokkaliitos CASCADE;
DROP TABLE IF EXISTS Tarkeysaste CASCADE;